version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    ports:
      - 7474:7474 # http
      - 7687:7687 # bolt